### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ca-shen98** [vitogit/sorter#1]
Hi, I am wondering what license you would have for using this project. Thanks :)

**Comment by waldyrious** [comment]
[According to `package.json`](https://github.com/vitogit/sorter/blob/master@%7B2020-05-07%7D/package.json#L31) the license is MIT, but a file with the actual license text is also needed. I'd say this issue can be resolved by simply submitting a PR adding a `LICENSE` file with [these contents](https://choosealicense.com/licenses/mit/).

**Comment by vitogit** [comment]
It's MIT. Resolved by this PR https://github.com/vitogit/sorter/pull/2 Thanks for the PR
